### ISSUE TITLE
Use `feature` to track the `ignore_logprob` flag?

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#45]
Seems more consistent to use a Feature dictionary to track this type of graph information vs adding it to the tag of the nodes.

Is there any downside?

**Comment by brandonwillard** [comment]
> Is there any downside?

There's a little more overhead, but it's nothing to worry about.

A `Feature` probably would be better, if only to keep things off of the graph elements so that they can be treated as truly immutable.  This also goes hand-in-hand with the overall theme of https://github.com/aesara-devs/aesara/issues/362.

**Comment by ricardoV94** [comment]
Should we just remove the ignore_logprob or is it still needed?

**Comment by brandonwillard** [comment]
> Should we just remove the ignore_logprob or is it still needed?

Yeah, I believe we aren't using it at the moment, so removing it should be easy.
