### ISSUE TITLE
Raise NotImplementedError when factorized_joint_logprob cannot retrieve terms for every value variable

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#90]
This is a follow up on a discussion that started in https://github.com/aesara-devs/aeppl/pull/22#discussion_r736279307

I believe that whenever aeppl cannot provide a rewrite for a given graph the safest way to proceed is to raise an exception. In the following snippet the returned output is not a "joint_lopgrob" graph at all. The slightly obscure warning that is raised right now sounds insufficient. Users should not be expected to know what kind of graphs aeppl will be able to parse or not, and have to investigate the graph to see if some terms happen to be missing.

```python
import aesara.tensor as at
import aeppl

x_rv = at.random.normal(name="x")
y_rv = at.cos(x_rv)

z_rv = at.random.normal(name='z')  # Just so that the returned output is not `None`

y_vv = y_rv.clone()
z_vv = z_rv.clone()

aeppl.joint_logprob({y_rv: y_vv, z_rv: z_vv})
```
```
UserWarning: Found a random variable that was neither among the observations nor the conditioned variables: normal_rv{0, (0, 0), floatX, False}(RandomGeneratorSharedVariable(<Generator(PCG64) at 0x7FDFC27D6D60>), TensorConstant{[]}, TensorConstant{11}, TensorConstant{0.0}, TensorConstant{1.0})
```
I suggested in that PR to add a simple check at the end of `factorized_joint_logprob` of the form of:

```python
missing_value_terms = set(original_values.values()) - set(logprob_vars.keys()) 
if missing_value_terms:
    raise NotImplementedError(
        f"The logprob terms for the following value variables could not be derived: {missing_value_terms}"
    )
```

**Comment by brandonwillard** [comment]
> The slightly obscure warning that is raised right now sounds insufficient.

Let's start with exactly why that warning is insufficient and how you want to address those inefficiencies.

> Users should not be expected to know what kind of graphs aeppl will be able to parse or not, and have to investigate the graph to see if some terms happen to be missing.

They aren't.  The only thing users are expected to know is the set of terms in their model graphs for which they want to construct log-probability graphs.  That's it.

Also, nothing about improved error messages would require them to know less about the graphs with which they're working.  If a user received more/better error messages from `factorized_joint_logprob`, those messages would only help the user better understand their graphs, but it wouldn't prevent them from needing to read or understand the content of the error messages in order to successfully use AePPL.

For instance, if there are more measurable terms in the graph that are unknown to the user, that doesn't matter, because it's not `factorized_joint_logprob`'s job to tell the user about the graphs they're using&mdash;unless something irrevocably conflicts with its actual function.

A function could be made that informs the user of such things, and that could be used inside a distinct interface to `factorized_joint_logprob`, but extending the scope of `factorized_joint_logprob` to handle unrelated user-level debugging or provide information about its inputs is not a helpful change.


More generally, we can't&mdash;and shouldn't&mdash;make unnecessary assumptions about potentially measurable terms that do not have value variables assigned to them.  The types of (sub-)graphs that are measurable will change over time and with new features, and there's even reason to believe that more than one log-probability formulation will be possible in certain cases.


> I suggested in that PR to add a simple check at the end of `factorized_joint_logprob` of the form of:

What exactly is the snippet of code expected to do, and in exactly which ways is that an improvement?

There are definitely improvements that could be made to the current error messages/warnings, but we need to be very clear on what those are and the assumptions that might underlie them.

**Comment by ricardoV94** [comment]
>More generally, we can't—and shouldn't—make unnecessary assumptions about potentially measurable terms that do not have value variables assigned to them. The types of (sub-)graphs that are measurable will change over time and with new features, and there's even reason to believe that more than one log-probability formulation will be possible in certain cases.

I am not speaking about measurable terms that do not have value variables at all. I am speaking of the case where a user explicitly requests `joint_logprob({rv1: vv1, rv2: vv2})` and receives a graph where there is no `vv1`, as in my example below. 

In `factorized_joint_logprob` we know that the user expects an output with `{at.scalar('vv'): logp_term}`, so it seems perfectly reasonable to raise if we are not returning this by the end.

> >    I suggested in that PR to add a simple check at the end of factorized_joint_logprob of the form of:

> What exactly is the snippet of code expected to do, and in exactly which ways is that an improvement?

This would make this snippet:

```python
import aesara.tensor as at
import aeppl

x = at.random.normal()
y = at.random.normal()

cos_x = at.cos(x)
clip_y = at.clip(y, -1, 1)

cos_x_vv = at.scalar('cos_x_vv')
clip_y_vv = at.scalar('clip_y_vv')


aeppl.joint_logprob({cos_x: cos_x_vv, clip_y: clip_y_vv})
```
Raise a message like:
```
NotImplementedError: A logprob term could not be derived for the value_variable `cos_x_vv`
```

Right now we issue a warning that hints something may have gone wrong, but whose main purpose is something different:
```
UserWarning: Found a random variable that was neither among the observations nor the conditioned variables: normal_rv{0, (0, 0), floatX, False}(RandomGeneratorSharedVariable(<Generator(PCG64) at 0x7F54698B7580>), TensorConstant{[]}, TensorConstant{11}, TensorConstant{0.0}, TensorConstant{1.0})
```

My point is that the explicit error seems quite useful. The user can now probably figure out that we don't have rewrites for `cos(rv)`, whereas without it :
1. They might not realize they are not getting what they want until they try to create a function and get an `UnusedInput` 
2. Even if they realized from the warning, they would have more trouble investigating which of the terms is not being parsed. 

This is useful not only for the case where we don't have implemented logprobs, but also if they specify an invalid graph, such as specifying a value variable for a base RV and a deterministic transformation of it. Anytime we fail to do all the rewrites `{rv: vv}` specified by the user we can probably be certain we are not returning the object they expect.

If we change the API in the future, in that it no longer is supposed to try to recover a logprob term for each value variable, this check wouldn't make sense anymore. But right now this seems to be the API contract
